webapp:
    static_dir_path: dist

    data:
        schedule_file_path: flask/data/schedule.dat
        log_file_path: flask/data/log.db
        stat_dir_path: /dev/shm/rasp-shutter

sensor:
    influxdb:
        url: http://proxy.green-rabbit.net:8086
        token: TUi-cgEEDqEeD1o14fLaH6FdEgMoeqShRYlCHxuo63weJ5Nnmze_MFqRHJ0XeGlMS9r_1iZe3-HGgJDqZ9bqRA==
        org: home
        bucket: sensor

    lux:
        name: 屋外の照度
        measure: sensor.rasp
        hostname: rasp-weather-1
    solar_rad:
        name: 太陽の日射量
        measure: sensor.rasp
        hostname: rasp-weather-1

location:
    latitude: 35.6895
    longitude: 139.6917

metrics:
    data: flask/data/metrics.db

slack:
    bot_token: xoxb-000000000000-0000000000000-000000000000000000000000

    from: Shutter

    error:
        channel:
            name: "#error"
            id: XXXXXXXXXX
        interval_min: 180

liveness:
    file:
        scheduler: /dev/shm/rasp-shutter/liveness/scheduler

shutter:
    - name: リビング①
      endpoint:
          open: http://127.0.0.1:5000/rasp-shutter/api/dummy/open
          close: http://127.0.0.1:5000/rasp-shutter/api/dummy/close

    - name: リビング②
      endpoint:
          open: http://127.0.0.1:5000/rasp-shutter/api/dummy/open
          close: http://127.0.0.1:5000/rasp-shutter/api/dummy/close
